services:
  - type: web
    name: celestial-qbies-engine
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn coordinator.app:app --host 0.0.0.0 --port $PORT"
